--DATA 검색
SELECT * FROM TESTER;
SELECT * FROM STUDENT;
SELECT * FROM STUDENTCAPTURE;
SELECT * FROM STUDENTANSWER;

--웹캠 링크 업데이트 (임의로 사용)
UPDATE STUDENTCAPTURE SET CAPTURE_CONTENT='SSUITA033212201624232020101217-07-05.mp4';

--DATA 기본 정보 생성--
----TESTER 테이블 디폴트 데이터
INSERT INTO TESTER(TEST_CODE, USER_ID, TEST_NUMOFQUST, TEST_DELFLAG) 
VALUES('A033212', 'SSUIT', '5','N');

----STUDENT 테이블 디폴트 데이터
INSERT INTO STUDENT(STUDENT_CODE, TEST_CODE, USER_ID,
	STUDENT_DEPTM, STUDENT_NAME, STUDENT_EMAIL, TEST_FLAG) 
VALUES('20162579','A033212', 'SSUIT', '글로벌미디어학부', '손주애', '9apples1718@gmail.com', 'N');

INSERT INTO STUDENT(STUDENT_CODE, TEST_CODE, USER_ID,
	STUDENT_DEPTM, STUDENT_NAME, STUDENT_EMAIL, TEST_FLAG) 
VALUES('20162423','A033212', 'SSUIT', '간호학과', '백주영', 'qorwndud4965@naver.com', 'N');

INSERT INTO STUDENT(STUDENT_CODE, TEST_CODE, USER_ID,
	STUDENT_DEPTM, STUDENT_NAME, STUDENT_EMAIL, TEST_FLAG) 
VALUES('20162580','A033212', 'SSUIT', '유아교육과', '유하경', 'shyoo447@naver.com', 'N');

UPDATE STUDENT SET STUDENT_EMAIL ='daon9apples@naver.com'
WHERE STUDENT_CODE ='20162579';

UPDATE STUDENT SET STUDENT_DEPTM='글로벌미디어학부'
WHERE STUDENT_CODE='20162579';

UPDATE STUDENT SET TEST_FLAG='N'
WHERE STUDENT_CODE='20162423';

UPDATE STUDENTANSWER SET STUDENT_SCORE='' , STUDENT_ANSWER='';

INSERT INTO STUDENT(STUDENT_CODE, TEST_CODE, USER_ID,
	STUDENT_DEPTM, STUDENT_NAME, STUDENT_EMAIL, TEST_FLAG) 
VALUES('20162625','A033212', 'SSUIT', '글로벌미디어학부', '현은빈', 'dmsqlsgus@naver.com', 'N');

INSERT INTO STUDENT(STUDENT_CODE, TEST_CODE, USER_ID,
	STUDENT_DEPTM, STUDENT_NAME, STUDENT_EMAIL, TEST_FLAG) 
VALUES('20162623','A033212', 'SSUIT', '글로벌미디어학부', '최지영', 'curryisgood@naver.com', 'N');

----STUDENTANSWER 테이블 디폴트 데이터
INSERT INTO STUDENTANSWER (TEST_NUM, STUDENT_CODE, TEST_CODE, USER_ID, STUDENT_SCORE) 
VALUES ('1', '20162623', 'A033212', 'SSUIT', '20');

INSERT INTO STUDENTANSWER (TEST_NUM, STUDENT_CODE, TEST_CODE, USER_ID, STUDENT_SCORE) 
VALUES ('2', '20162623', 'A033212', 'SSUIT', '17');

INSERT INTO STUDENTANSWER (TEST_NUM, STUDENT_CODE, TEST_CODE, USER_ID, STUDENT_SCORE) 
VALUES ('3', '20162623', 'A033212', 'SSUIT', '15');

INSERT INTO STUDENTANSWER (TEST_NUM, STUDENT_CODE, TEST_CODE, USER_ID, STUDENT_SCORE) 
VALUES ('4', '20162623', 'A033212', 'SSUIT', '20');

INSERT INTO STUDENTANSWER (TEST_NUM, STUDENT_CODE, TEST_CODE, USER_ID, STUDENT_SCORE) 
VALUES ('5', '20162623', 'A033212', 'SSUIT', '20');

INSERT INTO STUDENTANSWER (TEST_NUM, STUDENT_CODE, TEST_CODE, USER_ID, STUDENT_SCORE) 
VALUES ('6', '20162623', 'A033212', 'SSUIT', '20');

INSERT INTO STUDENTANSWER (TEST_NUM, STUDENT_CODE, TEST_CODE, USER_ID, STUDENT_SCORE) 
VALUES ('7', '20162623', 'A033212', 'SSUIT', '10');

INSERT INTO STUDENTANSWER (TEST_NUM, STUDENT_CODE, TEST_CODE, USER_ID, STUDENT_SCORE) 
VALUES ('8', '20162623', 'A033212', 'SSUIT', '5');

INSERT INTO STUDENTANSWER (TEST_NUM, STUDENT_CODE, TEST_CODE, USER_ID, STUDENT_SCORE) 
VALUES ('9', '20162623', 'A033212', 'SSUIT', '12');

INSERT INTO STUDENTANSWER (TEST_NUM, STUDENT_CODE, TEST_CODE, USER_ID, STUDENT_SCORE) 
VALUES ('10', '20162623', 'A033212', 'SSUIT', '20');

--웹캠 정보 세팅
INSERT INTO STUDENTCAPTURE (TEST_CODE, STUDENT_CODE, USER_ID)
VALUES ('A033212', '20162623', 'SSUIT');

--1.학생 정보 출력(학번, 이름, 이메일, 학과, 응시 여부)
SELECT STUDENT_CODE, STUDENT_NAME, STUDENT_EMAIL, STUDENT_DEPTM, TEST_FLAG
FROM STUDENT
WHERE TEST_CODE='A033212' AND USER_ID='SSUIT';

--2.UUID생성 (메일로 보내기전에 생성-같은 학교, 같은 시험 보는 학생들에게 동일하게 부여)
UPDATE STUDENT SET STUDENT_UUID=''
WHERE STUDENT_CODE='20162579' AND TEST_CODE='A033212' AND USER_ID='SSUIT';

--3.메일로 보낼 정보들(학번, 학과, 학생이름, 학생이메일, UUID, 링크)
SELECT STUDENT_CODE, TEST_CODE, USER_ID, STUDENT_DEPTM,
STUDENT_NAME, STUDENT_EMAIL, STUDENT_UUID, TEST_LINK
FROM STUDENT
WHERE USER_ID='SSUIT' AND TEST_CODE='A033212' AND STUDENT_CODE='20162579';

--4.수험자 시험응시 응시로그인 확인(시험코드, 학번, UUID)
SELECT STUDENT_CODE, STUDENT_NAME, STUDENT_UUID
FROM STUDENT
WHERE USER_ID='SSUIT' AND TEST_CODE='A033212'
AND STUDENT_CODE='20162579' AND STUDENT_UUID='0f4d0b29-023e-4e5d-970d-8689c1d31dea';

--5.IP 정보 입력(응시로그인하는 순간)
UPDATE STUDENT SET STUDENT_IP='190.803.123'
WHERE USER_ID='SSUIT' AND TEST_CODE='A033212' 
AND STUDENT_CODE='20162579' AND TEST_FLAG='N';

--6.시험응시 여부 'Y'로 갱신
SELECT TEST_FLAG
FROM STUDENT
WHERE USER_ID='SSUIT' AND TEST_CODE='A033212'
AND STUDENT_CODE='20162579'

UPDATE STUDENT SET TEST_FLAG='Y'
WHERE USER_ID='SSUIT' AND TEST_CODE='A033212'
AND STUDENT_CODE='20162579';

--7.답안 저장. 응시자가 시험 본 답안을 저장함.
UPDATE STUDENTANSWER SET STUDENT_ANSWER='케스케이드 모델', STUDENT_SCORE='30'
WHERE USER_ID='SSUIT' AND TEST_CODE='A033212'
AND STUDENT_CODE='20162579' AND TEST_NUM='1';

--8.시험지 학생별 조회(점수 합계, IP, 웹캠 영상, 학생 답, 답안 유사성)
SELECT STUDENT_NAME, STUDENT_CODE, 
STUDENT_DEPTM, STUDENT_IP, STUDENT_EMAIL
FROM STUDENT
WHERE USER_ID='SSUIT' AND TEST_CODE ='A033212'
AND STUDENT_CODE ='20162579';
--9. 전체 총점
SELECT SUM(STUDENT_SCORE) FROM STUDENTANSWER
	WHERE USER_ID='SSUIT' AND TEST_CODE ='A033212'
	AND STUDENT_CODE ='20162579';

--10.답안 테이블 답안 및 점수 조회
SELECT TEST_NUM, STUDENT_SCORE, STUDENT_ANSWER
FROM STUDENTANSWER
WHERE USER_ID='SSUIT' AND TEST_CODE ='A033212'
AND STUDENT_CODE ='20162579';

--11.웹캠 URL 삽입
INSERT INTO STUDENTCAPTURE (VIDEO_NUM, STUDENT_CODE, TEST_CODE, USER_ID, CAPTURE_CONTENT)
VALUES('1', '20162579', 'A033212', 'SSUIT', 'http://ssu.ac.kr');

DELETE FROM STUDENTCAPTURE s ;

--12.웹캠 URL가져오기
SELECT CAPTURE_CONTENT FROM STUDENTCAPTURE
WHERE TEST_CODE='A033212' AND USER_ID='SSUIT' AND STUDENT_CODE='20162579';

